service: tabnews-search

frameworkVersion: "3"

provider:
  name: aws
  region: us-east-1
  runtime: nodejs16.x
  deploymentMethod: direct
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - "s3:GetObject"
            - "s3:PutObject"
          Resource:
            - "arn:aws:s3:::tn-search/*"

plugins:
  - serverless-offline

functions:
  search:
    handler: functions/search.search
    timeout: 10
    events:
      - httpApi: "GET /search"
  fetchNew:
    handler: functions/fetchNew.fetchNew
    timeout: 300
  fetchAll:
    handler: functions/fetchAll.fetchAll
    timeout: 900
