service: tabnews-search

frameworkVersion: "3"

provider:
  name: aws
  region: us-east-1
  runtime: nodejs16.x
  deploymentMethod: direct
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - "s3:*Object"
          Resource:
            - "arn:aws:s3:::tn-search/*"

plugins:
  - serverless-offline

functions:
  search:
    handler: functions/search.search
    timeout: 10
    events:
      - httpApi: "GET /search"
  fetchNew:
    handler: functions/fetchNew.fetchNew
    timeout: 300
    events:
      - schedule: rate(2 hours)
  fetchAll:
    handler: functions/fetchAll.fetchAll
    timeout: 900
    events:
      - schedule: cron(0 3 * * ? *)
  tags:
    handler: functions/tags.tags
    timeout: 300
    events:
      - schedule: rate(3 hours)
